server:
  port: 9000
spring:
  application:
    name: cards_service
  datasource:
    url: jdbc:h2:mem:testdb1
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  # rabbitmq
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"