spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0.0"

accounts:
  message: "Welcome to EazyBank cards related Production APIs "
  contactDetails:
    name: "Nasim Kabir - SWE Lead"
    email: "nasim@gmail.com"
  onCallSupport:
    - (+880) 1837745754
    - (+880) 1837745758
