# services
services:
  accounts:
    image: "nasimkabir/accounts_service:v1"
    container_name: accounts_ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nasim_network
  loans:
    image: "nasimkabir/loans_service:v1"
    container_name: loans_service
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nasim_network
  cards:
    image: "nasimkabir/cards_service:v1"
    container_name: cards_service
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nasim_network
networks:
  nasim_network:
    driver: "bridge"