global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'accounts-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'accounts-service:8081' ]
  - job_name: 'loans-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'loans-service:8090' ]
  - job_name: 'cards-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'cards-service:9000' ]
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver:8761' ]
  - job_name: 'api-gateway-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'api-gateway-server:8072' ]
  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'configserver:8071' ]

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s