services:
  configserver:
    image: "nasimkabir/config_server:v7"
    container_name: config_server
    ports:
      - "8071:8071"
    extends:
      file: common-config.yml
      service: microservice-base-config
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8071/actuator/health || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 30
      start_period: 60s


  accounts:
    image: "nasimkabir/accounts_service:v5"
    container_name: accounts_service
    ports:
      - "8080:8080"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "nasimkabir/loans_service:v3"
    container_name: loans_service
    ports:
      - "8090:8090"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "nasimkabir/cards_service:v3"
    container_name: cards_service
    ports:
      - "9000:9000"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  nasim_network:
    driver: bridge