spring:
  application:
    name: api-gateway-server
  config:
    import: "optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
          # global-response-timeout: 5000 for all services applicable
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1s
      connect-timeout: 2s
#      httpclient:
#        connect-timeout: 5000
#        response-timeout: 5s


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG



# resilience4j:
resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        permitted-number-of-calls-in-half-open-state: 2
