server:
  port: 8090
spring:
  application:
    name: loans_service
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb?useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true




management:
  endpoints:
    web:
      exposure:
        include: "*"




