services:
  configserver:
    image: nasimkabir/config_server:v10
    container_name: configserver
    hostname: configserver
    environment:
      - SPRING_APPLICATION_NAME=configserver
      - SERVICE_NAME=configserver
    ports:
      - "8071:8071"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8071/actuator/health || exit 1" ]
      #      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s
    extends:
      file: common-config.yml
      service: microservice-base-config


  eurekaserver:
    image: nasimkabir/eureka_server:v3
    container_name: eurekaserver
    hostname: eurekaserver
    environment:
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
    ports:
      - "8761:8761"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1" ]
      #      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "nasimkabir/accounts_service:v10"
    container_name: accounts_service
    hostname: accounts-service
    environment:
      - SPRING_APPLICATION_NAME=accounts-service
      - SERVICE_NAME=accounts-service
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "nasimkabir/loans_service:v10"
    container_name: loans_service
    hostname: loans-service
    environment:
      - SPRING_APPLICATION_NAME=loans-service
      - SERVICE_NAME=loans-service
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8090:8090"
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config


  cards:
    image: "nasimkabir/cards_service:v10"
    container_name: cards_service
    hostname: cards-service
    environment:
      - SPRING_APPLICATION_NAME=cards-service
      - SERVICE_NAME=cards-service
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "9000:9000"
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config


networks:
  nasim_network:
    driver: bridge
    attachable: true