build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related Test APIs "
  contactDetails:
    name: "Cyrano Marita - Test Lead"
    email: "cyrano@eazybank.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467