server:
  port: 8071

spring:
  application:
    name: config_server
  profiles:
    active: native
cloud:
  config:
    server:
      native:
        search-locations: classpath:/config/
      fail-fast: true
    discovery:
      enabled: false